name: ColorPlugin   #플러그인 이름
version: 1.0       #플러그인 버전
main: com.Main #플러그인 패키지 이름.진입점 클래스 이름

commands:
  test:
    description: 컬러 서버 테스트 명령어입니다.
    usage: /test, /ㅋㄹ, /컬러 중 하나를 치면 작동합니다.
    aliases: [ ㅋㄹ, 컬러 ]